[package]
name = "rusty-relaxation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.30", features = ["thread-pool"] }
threadpool = "1.8.1"

[profile.release]
lto = "fat"
